package com.project.aws.crud.product.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.project.aws.crud.product.dto.ProductDTO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Mapeamento dos dados do Produto no banco de dados
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "product")
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String sku;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private BigDecimal price;

    public ProductDTO toDTO(){
        return ProductDTO.builder()
                         .id(this.id)
                         .name(this.name)
                         .sku(this.sku)
                         .description(this.description)
                         .price(this.price)
                         .build();
    }
}
