spring:
    application:
        name: aws-crud

amazon:
    aws:
        accesskey: '${AMAZON_AWS_ACESS_KEY:AKIAUCR5HXTBN3VUPG5J}'
        secretkey: '${AMAZON_AWS_SECRET_KEY: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}'
        region: '${AMAZON_AWS_REGION:us-east-1}'
    dynamodb:
        endpoint: '${AMAZON_DYNAMODB_ENDPOINT:dynamodb.us-east-1.amazonaws.com}'