spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: '${SPRING_CLOUD_GATEWAY_URI_EMPLOYEE_SERVICE:http://localhost:9001/}'
          predicates:
            - Path=/employees/**
        - id: PRODUCT-SERVICE
          uri: '${SPRING_CLOUD_GATEWAY_URI_PRODUCT_SERVICE:http://localhost:9002/}'
          predicates:
            - Path=/products/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '${EUREKA_CLIENT_SERVICE-URL_DEFAULT_ZONE:http://localhost:8761/eureka/}'
  instance:
    hostname: '${EUREKA_INSTANCE_HOSTNAME:localhost}'