spring:
    application:
        name: employee-service

server:
    port: 9001

amazon:
    aws:
        accesskey: '${AMAZON_AWS_ACESS_KEY:AKIAUCR5HXTBN3VUPG5J}'
        secretkey: '${AMAZON_AWS_SECRET_KEY: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}'
        region: '${AMAZON_AWS_REGION:us-east-1}'
    dynamodb:
        endpoint: '${AMAZON_DYNAMODB_ENDPOINT:dynamodb.us-east-1.amazonaws.com}'

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: '${EUREKA_CLIENT_SERVICE-URL_DEFAULT_ZONE:http://localhost:8761/eureka/}'
    instance:
        hostname: '${EUREKA_INSTANCE_HOSTNAME:localhost}'